### ISSUE TITLE
docker-compose file doesn't work

### ISSUE THREAD

**Issue by yngvark** [Kong/docker-kong#248]
I was simply trying to run with docker compose, but it didn't work.

```shell
$ docker-compose up
Creating network "compose_kong-net" with the default driver
Creating volume "compose_kong_data" with default driver
Creating compose_db_1 ... done
Creating compose_kong-migrations_1 ... done
Creating compose_kong_1            ... done
Attaching to compose_db_1, compose_kong-migrations_1, compose_kong_1
db_1               | The files belonging to this database system will be owned by user "postgres".
db_1               | This user must also own the server process.
db_1               | 
db_1               | The database cluster will be initialized with locale "en_US.utf8".
db_1               | The default database encoding has accordingly been set to "UTF8".
db_1               | The default text search configuration will be set to "english".
db_1               | 
db_1               | Data page checksums are disabled.
db_1               | 
db_1               | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1               | creating subdirectories ... ok
db_1               | selecting default max_connections ... 100
db_1               | selecting default shared_buffers ... 128MB
db_1               | selecting dynamic shared memory implementation ... posix
db_1               | creating configuration files ... ok
db_1               | creating template1 database in /var/lib/postgresql/data/base/1 ... ok
db_1               | initializing pg_authid ... ok
db_1               | setting password ... ok
db_1               | initializing dependencies ... ok
db_1               | creating system views ... ok
db_1               | loading system objects' descriptions ... ok
db_1               | creating collations ... ok
db_1               | creating conversions ... ok
db_1               | creating dictionaries ... ok
db_1               | setting privileges on built-in objects ... ok
db_1               | creating information schema ... ok
db_1               | loading PL/pgSQL server-side language ... ok
db_1               | vacuuming database template1 ... ok
db_1               | copying template1 to template0 ... ok
db_1               | copying template1 to postgres ... ok
db_1               | syncing data to disk ... ok
db_1               | 
db_1               | WARNING: enabling "trust" authentication for local connections
db_1               | You can change this by editing pg_hba.conf or using the option -A, or
db_1               | --auth-local and --auth-host, the next time you run initdb.
db_1               | 
db_1               | Success. You can now start the database server using:
db_1               | 
db_1               |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1               | 
db_1               | waiting for server to start....LOG:  database system was shut down at 2019-04-01 11:00:25 UTC
db_1               | LOG:  MultiXact member wraparound protections are now enabled
db_1               | LOG:  autovacuum launcher started
db_1               | LOG:  database system is ready to accept connections
db_1               |  done
db_1               | server started
db_1               | CREATE DATABASE
db_1               | 
db_1               | 
db_1               | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1               | 
db_1               | LOG:  received fast shutdown request
db_1               | waiting for server to shut down...LOG:  aborting any active transactions
db_1               | .LOG:  autovacuum launcher shutting down
db_1               | LOG:  shutting down
db_1               | LOG:  database system is shut down
db_1               |  done
db_1               | server stopped
db_1               | 
db_1               | PostgreSQL init process complete; ready for start up.
db_1               | 
db_1               | LOG:  database system was shut down at 2019-04-01 11:00:27 UTC
db_1               | LOG:  MultiXact member wraparound protections are now enabled
db_1               | LOG:  autovacuum launcher started
db_1               | LOG:  database system is ready to accept connections
kong-migrations_1  | No such command for migrations: bootstrap
kong-migrations_1  | 
kong-migrations_1  | Usage: kong migrations COMMAND [OPTIONS]
kong-migrations_1  | 
kong-migrations_1  | Manage Kong's database migrations.
kong-migrations_1  | 
kong-migrations_1  | The available commands are:
kong-migrations_1  |  list   List migrations currently executed.
kong-migrations_1  |  up     Execute all missing migrations up to the latest available.
kong-migrations_1  |  reset  Reset the configured database (irreversible).
kong-migrations_1  | 
kong-migrations_1  | Options:
kong-migrations_1  |  -c,--conf        (optional string) configuration file
kong-migrations_1  |  -y,--yes         assume "yes" to prompts and run non-interactively
kong-migrations_1  |  --v              verbose
kong-migrations_1  |  --vv             debug
kong-migrations_1  | No such command for migrations: bootstrap
kong-migrations_1  | 
kong-migrations_1  | Usage: kong migrations COMMAND [OPTIONS]
kong-migrations_1  | 
kong-migrations_1  | Manage Kong's database migrations.
kong-migrations_1  | 
kong-migrations_1  | The available commands are:
kong-migrations_1  |  list   List migrations currently executed.
kong-migrations_1  |  up     Execute all missing migrations up to the latest available.
kong-migrations_1  |  reset  Reset the configured database (irreversible).
kong-migrations_1  | 
kong-migrations_1  | Options:
kong-migrations_1  |  -c,--conf        (optional string) configuration file
kong-migrations_1  |  -y,--yes         assume "yes" to prompts and run non-interactively
kong-migrations_1  |  --v              verbose
kong-migrations_1  |  --vv             debug
compose_kong-migrations_1 exited with code 1
compose_kong-migrations_1 exited with code 1
kong_1             | 2019/04/01 11:00:58 [warn] 1#0: [lua] log.lua:63: log(): postgres database 'kong' is missing migration: (response-transformer) 2016-05-04-160000_resp_trans_schema_changes
kong_1             | nginx: [warn] [lua] log.lua:63: log(): postgres database 'kong' is missing migration: (response-transformer) 2016-05-04-160000_resp_trans_schema_changes
kong_1             | 2019/04/01 11:00:58 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:200: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
kong_1             | stack traceback:
kong_1             | 	[C]: in function 'assert'
kong_1             | 	/usr/local/share/lua/5.1/kong/init.lua:200: in function 'init'
kong_1             | 	init_by_lua:3: in main chunk
kong_1             | nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:200: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
kong_1             | stack traceback:
kong_1             | 	[C]: in function 'assert'
kong_1             | 	/usr/local/share/lua/5.1/kong/init.lua:200: in function 'init'
kong_1             | 	init_by_lua:3: in main chunk
compose_kong-migrations_1 exited with code 1
Exception in thread Thread-10:
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 246, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.24/containers/092e490654246b79014ea1262117dcd50f695af2523b5486151f84c92b2f3443/attach?logs=0&stdout=1&stderr=1&stream=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose/cli/log_printer.py", line 233, in watch_events
  File "compose/container.py", line 215, in attach_log_stream
  File "compose/container.py", line 307, in attach
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 57, in attach
  File "site-packages/docker/api/client.py", line 385, in _read_from_socket
  File "site-packages/docker/api/client.py", line 296, in _get_raw_response_socket
  File "site-packages/docker/api/client.py", line 248, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error: Conflict ("b'container 092e490654246b79014ea1262117dcd50f695af2523b5486151f84c92b2f3443 is restarting, wait until the container is running'")

compose_kong_1 exited with code 1
```

**Comment by yngvark** [comment]
I tried changing to `services.kong-migrations.command` to `"kong migrations up"`, which fixed it.

So I think docker-compose.yaml should be updated to reflect the latest kong images.

**Comment by hutchic** [comment]
This repository includes a test to validate our `docker-compose.yml` which is currently passing and I can't reproduce your problem locally.

Are you using an older version of Kong as the migration command changed from `kong migrations up` *to* `kong migrations bootstrap`

```
cd docker-kong/compose/
git rev-parse --short HEAD
8880bcd
docker-compose up -d
docker-compose logs kong-migrations
...
kong-migrations_1  | 23 migrations processed
kong-migrations_1  | 23 executed
kong-migrations_1  | database is up-to-date

docker images
...
kong latest dcef86ee910a 2 days ago 98.4MB

docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

docker-compose version
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

**Comment by yngvark** [comment]
You are right, after deleting all kong related images, `docker-compose up` works.

I guess my "latest" tag was an older version then, as I've used kong in docker for probably the past 6 months.
